// <auto-generated />
namespace Task_MessageRepo_withoutDb.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class migrat : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(migrat));
        
        string IMigrationMetadata.Id
        {
            get { return "201908031105432_migrat"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
